name: Add USB Image to Release

on:
  release:
    types:
      - created

jobs:
  add-usb-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create USB Image
        run: |
            apt-get install grub-efi-amd64 parted kpartx
            ./create-usb-image.sh ${{ github.event.release.id }}

      - name: Upload USB Image to Release
        uses: actions/upload-release-asset@v1
        with:
          asset_path: /tmp/fos-usb.img
          asset_name: fos-usb.img
          release_id: ${{ github.event.release.id }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
